name: BlocksConverter
version: 2.0.3
api: [3.0.0]
author: matcracker
main: matcracker\BlocksConverter\Loader

permissions:
    blocksconverter.commands:
        description: Allows using all plugin commands
        default: op
        children:
            blocksconverter.command.convertqueue:
                description: Allows using /convertqueue command.
            blocksconverter.command.convert:
                description: Allows using /convert command.
            blocksconverter.command.toolblock:
                description: Allows using /toolblock command.